# Generated by Django 3.1.2 on 2020-11-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=500)),
                ('assigned_to', models.ManyToManyField(related_name='assigned', to='RandomizeApp.User')),
            ],
        ),
    ]
