# Generated by Django 3.1.2 on 2020-11-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RandomizeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='amazon',
            field=models.CharField(max_length=300, null=True, verbose_name='Amazon wishlist link: '),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='colors',
            field=models.CharField(max_length=300, null=True, verbose_name='Colors in home/room: '),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite',
            field=models.CharField(max_length=300, null=True, verbose_name='Favorite gift I have gotten: '),
        ),
        migrations.AddField(
            model_name='user',
            name='hobbies',
            field=models.CharField(max_length=300, null=True, verbose_name='Hobbies: '),
        ),
        migrations.AddField(
            model_name='user',
            name='like_more',
            field=models.CharField(max_length=300, null=True, verbose_name='I would like more of: '),
        ),
        migrations.AddField(
            model_name='user',
            name='pants',
            field=models.CharField(max_length=300, null=True, verbose_name='Pants size: '),
        ),
        migrations.AddField(
            model_name='user',
            name='plenty_of',
            field=models.CharField(max_length=300, null=True, verbose_name='I have plenty of: '),
        ),
        migrations.AddField(
            model_name='user',
            name='reference',
            field=models.CharField(max_length=300, null=True, verbose_name='Someone who knows what gifts I like: '),
        ),
        migrations.AddField(
            model_name='user',
            name='shirt',
            field=models.CharField(max_length=300, null=True, verbose_name='Shirt size:'),
        ),
        migrations.AddField(
            model_name='user',
            name='shoes',
            field=models.CharField(max_length=300, null=True, verbose_name='Shoe size: '),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='street',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='treat',
            field=models.CharField(max_length=300, null=True, verbose_name='Favorite Treat: '),
        ),
        migrations.AddField(
            model_name='user',
            name='want_secretly',
            field=models.CharField(max_length=300, null=True, verbose_name='Something I am hoping for christmas but have not told anyone: '),
        ),
        migrations.AddField(
            model_name='user',
            name='zip',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='assigned_to',
            field=models.ManyToManyField(null=True, related_name='assigned', to='RandomizeApp.User'),
        ),
    ]
