# Generated by Django 3.1.2 on 2020-11-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RandomizeApp', '0002_auto_20201109_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='amazon',
            field=models.CharField(max_length=300, null=True, verbose_name='Amazon wishlist link'),
        ),
        migrations.AlterField(
            model_name='user',
            name='colors',
            field=models.CharField(max_length=300, null=True, verbose_name='Colors in home/room'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite',
            field=models.CharField(max_length=300, null=True, verbose_name='Favorite gift I have gotten'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hobbies',
            field=models.CharField(max_length=300, null=True, verbose_name='Hobbies'),
        ),
        migrations.AlterField(
            model_name='user',
            name='like_more',
            field=models.CharField(max_length=300, null=True, verbose_name='I would like more of'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pants',
            field=models.CharField(max_length=300, null=True, verbose_name='Pants size'),
        ),
        migrations.AlterField(
            model_name='user',
            name='plenty_of',
            field=models.CharField(max_length=300, null=True, verbose_name='I have plenty of'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reference',
            field=models.CharField(max_length=300, null=True, verbose_name='Someone who knows what gifts I like'),
        ),
        migrations.AlterField(
            model_name='user',
            name='shirt',
            field=models.CharField(max_length=300, null=True, verbose_name='Shirt size'),
        ),
        migrations.AlterField(
            model_name='user',
            name='shoes',
            field=models.CharField(max_length=300, null=True, verbose_name='Shoe size'),
        ),
        migrations.AlterField(
            model_name='user',
            name='treat',
            field=models.CharField(max_length=300, null=True, verbose_name='Favorite Treat'),
        ),
        migrations.AlterField(
            model_name='user',
            name='want_secretly',
            field=models.CharField(max_length=300, null=True, verbose_name='Something I am hoping for christmas but have not told anyone'),
        ),
    ]
